automation:
  - id: automation_kitchen_handles_on_motion
    alias: Kitchen Handles on Motion
    description: ""
    trigger:
      - entity_id: group.kitchen_motion
        from: "off"
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.sleep_mode
        state: "off"
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.kitchen_handles
        data:
          transition: 3
          brightness_pct: 20
      - service: light.turn_on
        target:
          entity_id:
            - light.kitchen_shelves
        data:
          transition: 3
          brightness_pct: 100
    mode: single
