automation:
  - id: automation_kitchen_match_spots_front
    alias: Kitchen Match Spots Front
    description: 'Turn on kitchen back spots when front turned on'
    trigger:
      - platform: state
        entity_id: light.front_spots
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        target:
          entity_id: light.back_spots
    mode: single

  - id: automation_kitchen_match_spots_back
    alias: Kitchen Match Spots Back
    description: 'Turn on kitchen front spots when back turned on'
    trigger:
      - platform: state
        entity_id: light.back_spots
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        target:
          entity_id: light.front_spots
    mode: single