automation:
  - id: automation_corridor_empty
    alias: Corridor Empty
    trigger:
      - entity_id: group.utility_motion
        for:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
        platform: state
        to: 'off'
        from: 'on'
    condition: []
    action:
      - data:
          transition: 3
        service: light.turn_off
        target:
          entity_id:
            - light.corridor_spots
    mode: single
