binary_sensor:
  - name: Drive Person
    platform: mqtt
    state_topic: "frigate/drive/person"
    device_class: motion
    availability_topic: "frigate/available"
  - name: Front Door Person
    platform: mqtt
    state_topic: "frigate/frontdoor/person"
    device_class: motion
    availability_topic: "frigate/available"
  - name: Landing Cat
    platform: mqtt
    state_topic: "frigate/landing/cat"
    device_class: motion
    availability_topic: "frigate/available"
