default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations

logger:
  default: info

recorder:
  auto_purge: true
  purge_keep_days: 63
  db_url: !secret mariadb_connection_url

alexa: !include alexa.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
