# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

alexa:
  smart_home:
    locale: en-GB
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

recorder:
  auto_purge: true
  purge_keep_days: 63
  db_url: !secret mariadb_connection_url

  # Text to speech
tts:
  - platform: google_translate

bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: rest_of_world

fibaro:
  gateways:
    - url: !secret fibaro_url
      username: !secret fibaro_username
      password: !secret fibaro_password

lametric:
  client_id: !secret lametric_client_id
  client_secret: !secret lametric_client_secret

notify:
  name: lametric
  platform: lametric

climate:
  - platform: sensibo
    api_key: !secret sensibo_api

tahoma:
  username: !secret tahoma_username
  password: !secret tahoma_password
  exclude: [BridgeHUEComponent, HueLampHUEComponent, PodComponent]

device_tracker:
  - platform: mqtt
    devices:
      mqtt_howard_iphone: !secret mqtt_howard_iphone_mac
      mqtt_deb_iphone: !secret mqtt_deb_iphone_mac
    payload_home: "online"
    payload_not_home: "offline"
    source_type: bluetooth

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.112
    activity: Watch Plex
  - platform: harmony
    name: Garden Room
    host: 10.107.0.111
    activity: Watch Plex

surepetcare:
  username: !secret sureflap_username
  password: !secret sureflap_password
  pets: [107869]
  flaps: [113430, 166844, 151961]
  scan_interval: "01:00:00"

switch: !include switch.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
