homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations
  allowlist_external_dirs:
    - /config/www/cam_snaps

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

logger:
  default: warning

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

panel_custom:
  - name: server_control
    sidebar_title: Server Control
    sidebar_icon: mdi:cog-transfer
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/server_control"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

lovelace:
  mode: storage
  dashboards:
    ui-lego:
      mode: yaml
      title: Lego
      icon: mdi:toy-brick
      show_in_sidebar: true
      filename: ui-lego.yaml

recorder:
  auto_purge: true
  purge_keep_days: 90
  db_url: !secret mariadb_connection_url
  exclude:
    domains:
      - automation
      - camera
      - http
      - image_processing
      - select
      - sun
      - timer
      - updater
    entity_globs:
      - sensor.weather_*
      - sensor.dark_sky_*
      - sensor.*lux*
      - sensor.*_illuminance
      - sensor.hp_officejet_*
      - sensor.*_uv_*
      - sensor.*_ultraviolet
      - sensor.motion_recording_*
      - switch.ir_active_*
      - switch.record_always_*
      - switch.record_motion_*
      - switch.status_light_on_*
      - sensor.time*
      - sensor.date*
      - binary_sensor.sun_*
    entities:
      - sun.sun # Don't record sun data
      - sensor.daylight
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.hacs
      - sensor.mjolnir_last_update_trigger
      - sensor.mjolnir_average_active_pace
      - sensor.mjolnir_geocoded_location
      - sensor.mjolnir_bssid
      - sensor.mjolnir_sim_1
      - sensor.mjolnir_sim_2
      - sensor.mjolnir_floors_descended
      - sensor.mjolnir_floors_ascended
      - sensor.low_battery
      - sensor.critical_battery
      - sensor.network_ups_serial
      - sensor.server_ups_serial
      - binary_sensor.updater
      - sensor.icloud3_event_log # ignore the icloud3 event log
      - sensor.deborah_s_iphone_info
      - sensor.mjolnir_info
