- platform: snmp
  name: PDU3-1
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-2
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-3
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-4
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.4
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-5
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.5
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-6
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.6
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-7
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: PDU3-8
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.8
  payload_on: 1
  payload_off: 2
#
