- platform: snmp
  name: Vision
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: SFF
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Thanos
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Synology SSDs
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.4
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Synology Diskstation
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.5
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Synology HDDs
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.6
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Denon Amp
  host: 192.168.1.22
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.8
  payload_on: 1
  payload_off: 2

#

- platform: snmp
  name: Sonos Bathroom
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Landing
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Office
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Dressing Room
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.4
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Bedroom
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.5
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Living Room & Utility
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.6
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Hall
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Sonos Kitchen
  host: 192.168.1.23
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.8
  payload_on: 1
  payload_off: 2

#

- platform: snmp
  name: USG-PRO-4
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: US-24-250W
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: US-16-XG
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: US-48-500W
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.4
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Shield TV
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.5
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Xbox One X
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.6
  payload_on: 1
  payload_off: 2

- platform: snmp
  name: Apple TV
  host: 192.168.1.21
  baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
  payload_on: 1
  payload_off: 2
#
