binary_sensor:
  - platform: template
    sensors:
      elec_high_cost:
        friendly_name: "High Electric Cost"
        value_template: "{{ (states('sensor.electricity_demand_cost') | float(0)) > 20.0 }}"