binary_sensor:
  - platform: template
    sensors:
      agile_plunge:
        unique_id: agile_plunge
        friendly_name: "Agile Plunge"
        value_template: "{{ (states('sensor.electricity_demand_cost') | float(100)) < 0.0 }}"