sensor:
  - platform: template
    sensors:
      solaredge_grid_export:
        unique_id: solaredge_grid_export
        friendly_name: Grid Export
        unit_of_measurement: "kW"
        icon_template: "mdi:transmission-tower"
        value_template: "{{( ((states('sensor.solaredge_modbus_meter_1') | float(0)) / 1000.0 ) | round(1)) if states('sensor.solaredge_modbus_meter_1') | int(0) > 100 else 0.0  }}"

