sensor:
  - platform: template
    sensors:
      solar_direction:
        unique_id: solar_direction
        friendly_name: "SolarEdge Status"
        value_template: "{% set mapper = {1:'off',2:'off',3:'off',4:'import',5:'import',6:'off',7:'Fault',8:'Fault'} %}{{mapper[state_attr('sensor.solaredge_modbus','status')]}}"
        