sensor:
  - platform: template
    sensors:
      import_power:
        unique_id: import_power
        friendly_name: Import Power
        unit_of_measurement: "kW"
        value_template: "{% if (states('sensor.solaredge_modbus_meter_1') | float(0) ) < -50.0 %}{{( ((states('sensor.solaredge_modbus_meter_1') | float(0)) / -1000.0 ) | round(1))  }}{% else %}0.0{% endif %}"

