sensor:
  - platform: template
    sensors:
      solar_production:
        unique_id: solar_production
        friendly_name: "Solar Production"
        unit_of_measurement: 'kW'
        value_template: "{{ ((states('sensor.solaredge_modbus') | float(0) )/ 1000.0 ) | round(1) }}"     
        device_class: energy