sensor:
  - platform: template
    sensors:
      solaredge_ac_power_kw_output:
        unique_id: solaredge_ac_power_kw_output
        friendly_name: "AC Power Output"
        value_template: "{{ (state_attr('sensor.solaredge_modbus', 'ac_power_output') / 1000 ) | round(1) }}"
        unit_of_measurement: 'kW'
        device_class: power  