automation:
  - id: dishwasher_set_running_on_power_detected
    alias: 'Dishwasher: Set to running when power detected'
    trigger:
      - above: '10'
        entity_id: sensor.dishwasher_energy_apparentpower
        platform: numeric_state
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.dishwasher_status
            state: Dirty
          - condition: state
            entity_id: input_select.dishwasher_status
            state: Clean
          - condition: state
            entity_id: input_select.dishwasher_status
            state: Drying
    action:
      - data:
          entity_id: input_select.dishwasher_status
          option: Running
        service: input_select.select_option
    mode: single
