automation:
  - id: quooker_set_off_on_power_drop
    alias: 'Quooker: Set off on power drop'
    trigger:
      - platform: numeric_state
        entity_id: sensor.quooker_energy_apparentpower
        below: '3'
      - platform: homeassistant
        id: "start"
        event: start
      - platform: event
        id: "reload"
        event_type: automation_reloaded
    condition:
      - condition: numeric_state
        entity_id: sensor.quooker_energy_apparentpower
        below: '3'     
    action:
      - service: input_select.set_options
        target:
          entity_id: input_select.quooker_status
        data:
          options: Off
    mode: single
