sensor:
  - platform: template
    sensors:
      forecastsolar_tomorrow:
        friendly_name: ForecastSolar Tomorrow
        value_template: "{{ (states('sensor.energy_production_tomorrow_se')|float + states('sensor.energy_production_tomorrow_nw')|float ) | round(1) }}"
        unit_of_measurement: "kWh"
