automation:
  - id: automation_update_bojack_tracker
    alias: "Update Bojack Tracker"
    description: ""
    trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.fordpass_gps
    condition: []
    action:
      - service: device_tracker.see
        data:
          dev_id: bojack
          gps:
            - "{{ state_attr('sensor.fordpass_gps', 'latitude') }}"
            - "{{ state_attr('sensor.fordpass_gps', 'longitude') }}"
    mode: single
