automation:
  - id: powerwall_powercut_actions
    alias: "Powerwall: Turn off high loads and announce powercut"
    mode: single

    description: >
      Powercut handling

    trigger:
      - platform: state
        id: "grid_off"
        entity_id: binary_sensor.grid_status
        to: "off"
      - platform: state
        id: "supply_off"
        entity_id: binary_sensor.electricity_supply
        to: "off"

    action:
      - service: notify.slack
        data:
          title: Powercut!
          message: Grid power has failed.
      - service: notify.slack
        data:
          title: There is a powercut!
          message: "HotTub and Car Chargers switched off. Powerwall capacity is {{ states('sensor.powerwall_charge_corrected') }}%"
      # - service: script.zappi_mode_bojack
      #   data:
      #     mode: 'Stopped'
      # - service: script.zappi_mode_roadster
      #   data:
      #     mode: 'Stopped'
      - service: notify.slack
        data:
          title: "Hot Tub Power"
          message: "Entering rest mode during power cut."
      # - service: climate.set_temperature
      #   target:
      #     entity_id: climate.spa_climate
      #   data:
      #     temperature: 28
