sensor:
  - platform: template
    sensors:
      powerwall_charge_corrected:
        unique_id: powerwall_charge_corrected
        friendly_name: "Powerwall Charge"
        unit_of_measurement: '%'
        value_template: "{{ (((states('sensor.powerwall_charge') | float(0)) * 1.05) - 5.0 ) | int(0)  }}"
        device_class: battery